# Generated by Django 5.2.4 on 2025-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0002_alter_film_options_alter_film_img_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title_lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
