# Generated by Django 5.2.4 on 2025-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0003_film_title_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_adult',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
