# Generated by Django 5.2.4 on 2025-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0004_film_is_adult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='img_path',
            new_name='local_img_path',
        ),
        migrations.AddField(
            model_name='film',
            name='site_img_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
