# Generated by Django 5.2.6 on 2025-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0004_remove_actor_movies_remove_film_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='serials',
            field=models.ManyToManyField(blank=True, to='mainProject.serial'),
        ),
    ]
