# Generated by Django 5.2.6 on 2025-10-24 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainProject', '0005_actor_serials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('writing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Ужасно'), (2, '2 - Плохо'), (3, '3 - Неудовлетворительно'), (4, '4 - Ниже среднего'), (5, '5 - Средне'), (6, '6 - Выше среднего'), (7, '7 - Хорошо'), (8, '8 - Очень хорошо'), (9, '9 - Отлично'), (10, '10 - Шедевр')], null=True, verbose_name='Оценка')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-writing_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mainProject_content_6772aa_idx')],
            },
        ),
    ]
