# Generated by Django 5.2.4 on 2025-07-18 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0005_rename_img_path_film_local_img_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('local_img_path', models.URLField(blank=True, null=True)),
                ('site_img_path', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('title_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('is_adult', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
    ]
