# Generated by Django 5.2.4 on 2025-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0006_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('deathday', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('site_img_path', models.URLField(blank=True, null=True)),
                ('local_img_path', models.URLField(blank=True, null=True)),
                ('movies', models.ManyToManyField(blank=True, null=True, to='mainProject.film')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
    ]
