# Generated by Django 5.2.4 on 2025-07-21 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0007_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='release_date',
            new_name='first_air_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='film',
            name='title_lang',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='title_lang',
        ),
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='last_air_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
