# Generated by Django 5.2.4 on 2025-07-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0008_rename_release_date_serial_first_air_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
