# Generated by Django 5.2.4 on 2025-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0009_remove_actor_movies_actor_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
