# Generated by Django 5.2.4 on 2025-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0010_film_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
