# Generated by Django 5.2.6 on 2025-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0010_film_trailer_url_serial_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_private',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
