# Generated by Django 5.2.6 on 2025-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0011_serial_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
