# Generated by Django 5.2.6 on 2025-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0012_film_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='actors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
