# Generated by Django 5.2.6 on 2025-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
