# Generated by Django 5.2.6 on 2025-10-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0017_alter_message_options_alter_message_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='local_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='actors'),
        ),
        migrations.AlterField(
            model_name='film',
            name='local_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='local_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='serials/'),
        ),
    ]
