# Generated by Django 5.2.6 on 2025-10-20 11:15

from django.db import migrations


def change_local_img_paths(apps, schema_editor):
    Film = apps.get_model('mainProject', 'Film')
    films = Film.objects.all()
    for film in films:
        img_path = str(film.local_img_path)
        img_name = img_path.split('/')[-1]
        film.local_img_path = img_name
        film.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0018_alter_actor_local_img_path_alter_film_local_img_path_and_more'),
    ]

    operations = [
        migrations.RunPython(change_local_img_paths),
    ]
