# Generated by Django 5.2.6 on 2025-10-20 11:31

from django.db import migrations

def change_local_img_paths(apps, schema_editor):
    Model = apps.get_model('mainProject', 'Serial')
    objects = Model.objects.all()
    for object in objects:
        img_path = str(object.local_img_path)
        img_name = img_path.split('/')[-1]
        object.local_img_path = img_name
        object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0019_auto_20251020_1415'),
    ]

    operations = [
        migrations.RunPython(change_local_img_paths),
    ]
