# Generated by Django 5.2.6 on 2025-11-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название списка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание списка')),
                ('list_type', models.CharField(choices=[('favorite', 'Избранное'), ('watch_later', 'Смотреть позже'), ('watched', 'Просмотрено'), ('custom', 'Пользовательский список')], default='custom', max_length=20, verbose_name='Тип списка')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный список')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция в списке')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки пользователя')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to=settings.AUTH_USER_MODEL, verbose_name='Владелец списка')),
            ],
            options={
                'verbose_name': 'Элемент списка',
                'verbose_name_plural': 'Элементы списков',
                'ordering': ['user', 'list_type', 'position', '-added_at'],
                'indexes': [models.Index(fields=['user', 'list_type'], name='mainSite_us_user_id_ab6f10_idx'), models.Index(fields=['content_type', 'object_id'], name='mainSite_us_content_2b0db2_idx'), models.Index(fields=['user', 'created_at'], name='mainSite_us_user_id_8b6499_idx')],
                'unique_together': {('user', 'list_type', 'content_type', 'object_id'), ('user', 'title')},
            },
        ),
    ]
