# Generated by Django 5.2.6 on 2025-11-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainSite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция в списке')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки пользователя')),
            ],
            options={
                'verbose_name': 'Элемент списка',
                'verbose_name_plural': 'Элементы списков',
                'ordering': ['position', '-added_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользовательский список', 'verbose_name_plural': 'Пользовательские списки'},
        ),
        migrations.RemoveIndex(
            model_name='userlist',
            name='mainSite_us_content_2b0db2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together={('user', 'title')},
        ),
        migrations.AddField(
            model_name='listitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainSite.userlist', verbose_name='Список'),
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='position',
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['content_type', 'object_id'], name='mainSite_li_content_127c82_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['user_list', 'position'], name='mainSite_li_user_li_2f54f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('user_list', 'content_type', 'object_id')},
        ),
    ]
