# Generated by Django 5.2.6 on 2025-10-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='discription',
            new_name='description',
        ),
    ]
