# Generated by Django 5.2.6 on 2025-10-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_discription_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
